### ISSUE TITLE
Аукцион space token'ов с блокировкой GALTов

### ISSUE THREAD

**Issue by goodstemy** [andromedaspace/WIJG#21]

**Comment by IgorFrolov** [comment]
- Возможность ввода данных для проверки геохеша на статус в любой момент
- Возможность ввода данных геохеша для последующего выпуска токена 721

**Comment by Jonybang** [comment]
Реализация аукциона: https://github.com/andromedaspace/WIJG/pull/11 и https://github.com/andromedaspace/WIJG/pull/31
Реализация блокировки GALT при аукционе: https://github.com/andromedaspace/WIJG/pull/35

**Comment by Jonybang** [comment]
Геохеш реализован: https://github.com/andromedaspace/WIJG/pull/43
Сейчас это и есть tokenId, и при выпуске токена как раз используется geohash как tokenId
@IgorFrolov закрываем?
