### ISSUE TITLE
Реализовать логику epoch # 2. Делегаты выбраны на этапе генерации Вселенной

### ISSUE THREAD

**Issue by IgorFrolov** [andromedaspace/WIJG#63]

**Comment by npopeka** [comment]
Сценарий:
1. Пользователь выбрал "Эпоха 2 - Выбраны делегаты.
2. Сообщение "Вас выбрали делегатом" Да /нет.
3. Если ДА, то:
4. Появляются дополнительные пункты меню:
4.1. "Подписать транзакцию.
4.1.1. Если пользователь выбрал "Подписать транзакцию", то
4.1.2. Сообщение "Было предложено отправить Х (случайная сумма от 1% до 9% от баланса кошелька). Да / Нет.
4.1.3. Боты - делегаты случайно голосуют и по результатам выдается сообщение:
4.1.3.1 Если транзакция подписана - "Х ETH переведены на адрес <адрес>".
4.1.3.2. Если транзакция не подписана - "Транзакция не подписана"
4.2. "Инициировать отправку денег"

**Comment by IgorFrolov** [comment]
Необходимо придерживаться сценария в mindmap
