### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by IgorFrolov** [andromedaspace/WIJG#64]
`? How many tokens you want to buy? 100

Success!

? Ether balance: 500
? Ether balance: 500
GALT: 100
SPACE count: 0

What you want to do? Visit SPACE auction
? Which space you want to buy? 
? Which space you want to buy? SPACE #sxrfddkr: 66
(node:18794) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: false == true
(node:18794) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Jonybang** [comment]
было исправлена и была добавлена проверка с дружелюбным сообщением пользователю в https://github.com/andromedaspace/WIJG/pull/88
