### ISSUE TITLE
Аукцион. Внести новый уровень интерактивности

### ISSUE THREAD

**Issue by IgorFrolov** [andromedaspace/WIJG#73]
В сценарии создания пользователем ставки, создаем инстанс стороннего пользователя, который перебивает ставку рандомно.

**Comment by Jonybang** [comment]
беру в работу

**Comment by npopeka** [comment]
Делаем сейчас так:

Если баланс GALT>0, то есть пункт в меню "Купить землю". Иначе - нет.
Если пользователь выбрал "Купить землю", то:
2.1. Сообщение "Выберите землю" и список незанятых токенов ERC721. Незанятые токены . токены, принадлежащие адресу ДАО.
2.2. Формат вывода токенов - ГЕОХЕШ, минимальная ставка - ХХ, например
hdugrty ,минимальная ставка - 100 GALT
jsdiue ,минимальная ставка - 100 GALT
fhysn ,минимальная ставка - 100 GALT
2.3. Пользователь выбирает токены и нажимает enter.
2.4. Сообщение "Введите ставку".
2.5. Пользователь вводить ставку.
2.6. Если ставка < минимальной ставки, то "Ваша ставка меньше минимальной", - п. 2.4.
2.7. Если недостаточно средств, то "Недостаточно средств", п - 2.2
2.8. Происходит аукцион за 30 секунд, показывается индикатор.
2.9. До завершения отсчета случайно делается ставка ботом. Если событие произошло, то сообщение "Сделана ставка Х GALT, перебить"? Да/ нет.
2.91. Если да, то п. 2.4.
2.92. Если нет - 2.1.
В меню должен быть вариант "Выйти из аукциона" на каждом шаге.

**Comment by Jonybang** [comment]
Реализовано перебите ставки ботом в https://github.com/andromedaspace/WIJG/pull/82, а валидация действий пользователей сделана в https://github.com/andromedaspace/WIJG/pull/88

Логика таже что и обозначена, за исключением того, что пользователь указывает какой ценой он хочет перебить ставку

**Comment by Jonybang** [comment]
дубликат https://github.com/andromedaspace/WIJG/issues/80, нужно будет закрыть issue вместе
