### ISSUE TITLE
Токен GALT. Реализовать в интерфейсах получение/отправку 

### ISSUE THREAD

**Issue by IgorFrolov** [andromedaspace/WIJG#76]
Используем аккаунты/адреса из сформированной Вселенной

**Comment by npopeka** [comment]
На уровне интерфейса:

1. Пользователь выбирает пункт меню "Отправить GALT"
2. Появляется сообщение "Введите адрес получателя:"
3. Пользователь вставляет адрес из буфера, нажимает enter
4.  Если адрес не существует - сообщение "Адреса не существует", переход в п. 2.
5. Появляется сообщение "Введите количество"
6. Пользователь вводит количество токенов и нажимает Enter.
7. Если количества недостаточно, то сообщение "Указанного количества не хватает", переход в 5.
