### ISSUE TITLE
Аукцион. Реализовать сценарии и описать пункты меню

### ISSUE THREAD

**Issue by IgorFrolov** [andromedaspace/WIJG#80]
Если баланс GALT положительный, то пользователю добавляем пункты:
 - Сделать ставку на незанятый участок
 - Перебить ставку

Логику описываем исходя из текущего функционала аукциона.

**Comment by npopeka** [comment]
Делаем сейчас так:
1. Если баланс GALT>0, то есть пункт в меню "Купить землю". Иначе - нет.
2. Если пользователь выбрал "Купить землю", то:
2.1. Сообщение "Выберите землю" и список незанятых токенов ERC721. Незанятые токены . токены, принадлежащие адресу ДАО.
2.2. Формат вывода токенов - ГЕОХЕШ, минимальная ставка - ХХ, например 
hdugrty ,минимальная ставка - 100 GALT
jsdiue ,минимальная ставка - 100 GALT
fhysn ,минимальная ставка - 100 GALT
2.3. Пользователь выбирает токены и нажимает enter.
2.4. Сообщение "Введите ставку".
2.5. Пользователь вводить ставку. 
2.6. Если ставка < минимальной ставки, то "Ваша ставка меньше минимальной", - п. 2.4.
2.7. Если недостаточно средств, то "Недостаточно средств", п - 2.2
